# Generated by Django 6.0 on 2025-12-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('3rd_gender', '3rd Gender')], max_length=20)),
                ('fathers_name', models.CharField(max_length=200)),
                ('mothers_name', models.CharField(max_length=200)),
                ('gardians_name', models.CharField(blank=True, max_length=200, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('fathers_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mothers_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gardians_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('student_class', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('transport_method', models.CharField(choices=[('school_bus', 'School Bus'), ('other', 'Other')], max_length=50)),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student_class', 'name'],
            },
        ),
    ]
