# Generated by Django 6.0 on 2025-12-28 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0002_feesstructure_head_income_session_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, unique=True)),
                ('class_code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['age'],
            },
        ),
        migrations.CreateModel(
            name='FeesAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(default='Unnamed Account', max_length=100)),
                ('account_open', models.DateField()),
                ('account_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('account_close', models.DateField(blank=True, null=True)),
                ('register_page', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fees Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_class__age', 'first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Admission Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='primary_account_holder',
            field=models.BooleanField(default=False, verbose_name='Primary Account Holder'),
        ),
        migrations.AddField(
            model_name='student',
            name='rte',
            field=models.BooleanField(default=False, verbose_name='Right to Education'),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='dailyLedger.session'),
        ),
        migrations.AddField(
            model_name='student',
            name='srn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Student Registration Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='transport_method',
            field=models.BooleanField(default=False, verbose_name='Uses School Bus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_class', to='students.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.feesaccount'),
        ),
        migrations.CreateModel(
            name='SessionClassStudentMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Student Registration Number')),
                ('promoted_date', models.DateTimeField(blank=True, null=True, verbose_name='Promotion Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_student_maps', to='dailyLedger.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_class_maps', to='students.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_student_maps', to='students.class')),
            ],
            options={
                'verbose_name_plural': 'Session Class Student Maps',
                'ordering': ['session', 'student_class__age', 'student__first_name'],
                'unique_together': {('session', 'student_class', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tc_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book_diary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book_other', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_shirt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_pant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_tie', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_belt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_id_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyLedger.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='students.student')),
            ],
            options={
                'ordering': ['-session', 'student__first_name'],
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='dailyLedger.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.class')),
            ],
            options={
                'ordering': ['-date', 'student__first_name', 'student__last_name'],
                'unique_together': {('session', 'student', 'date')},
            },
        ),
    ]
