# Generated by Django 6.0 on 2025-12-20 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0011_expense_payment_type'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tc_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book_diary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book_other', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_shirt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_pant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_tie', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_belt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_id_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyLedger.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='students.student')),
            ],
            options={
                'ordering': ['-session', 'student__name'],
                'unique_together': {('student', 'session')},
            },
        ),
    ]
