# Generated by Django 6.0 on 2026-04-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_class_feesaccount_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nic_student_id',
            field=models.CharField(blank=True, db_column='NIC_Student_ID', max_length=100, null=True, verbose_name='NIC Student ID'),
        ),
    ]
