# Generated by Django 6.0 on 2025-12-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('account_open', models.DateField()),
                ('account_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('account_close', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fees Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
