# Generated by Django 6.0 on 2026-04-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_nic_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='book_set',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='uniform_hoody',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='uniform_sweater',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='uniform_t_shirt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
