# Generated by Django 6.0 on 2025-12-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_feesaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesaccount',
            name='account_name',
        ),
        migrations.AddField(
            model_name='feesaccount',
            name='name',
            field=models.CharField(default='Unnamed Account', max_length=100),
        ),
    ]
