# Generated by Django 6.0 on 2026-04-13 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0005_feesstructure_uniform_hoody_and_more'),
        ('students', '0004_studentaccount_book_set_studentaccount_uniform_hoody_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesAccountAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tc_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book_set', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book_diary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book_other', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_shirt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_pant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_sweater', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_hoody', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_t_shirt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_tie', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_belt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_id_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fees_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='students.feesaccount')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_account_agreements', to='dailyLedger.session')),
            ],
            options={
                'ordering': ['-session', 'fees_account__account_id'],
                'unique_together': {('fees_account', 'session')},
            },
        ),
    ]
