# Generated by Django 6.0 on 2026-04-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_feesaccountagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesaccountagreement',
            name='bus_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
