# Generated by Django 6.0 on 2025-12-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_feesaccount_account_name_feesaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
