# Generated by Django 6.0 on 2026-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_add_bus_fees_to_feesaccountagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesaccount',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
    ]
