# Generated by Django 6.0 on 2025-12-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_class_class_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesaccount',
            name='register_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
