# Generated by Django 6.0 on 2025-12-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_feesaccount_register_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_class', 'first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='studentaccount',
            options={'ordering': ['-session', 'student__first_name']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
