# Generated by Django 6.0 on 2025-12-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_options_alter_studentaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.feesaccount'),
        ),
        migrations.AddField(
            model_name='student',
            name='primary_account_holder',
            field=models.BooleanField(default=False, verbose_name='Primary Account Holder'),
        ),
        migrations.AddField(
            model_name='student',
            name='rte',
            field=models.BooleanField(default=False, verbose_name='Right to Education'),
        ),
        migrations.AddField(
            model_name='student',
            name='srn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Student Registration Number'),
        ),
    ]
