# Generated by Django 6.0 on 2025-12-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0011_expense_payment_type'),
        ('students', '0009_student_fees_account_student_primary_account_holder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_class__age', 'first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='dailyLedger.session'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_class', to='students.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='transport_method',
            field=models.CharField(choices=[('school_bus', 'School Bus'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
