# Generated by Django 6.0 on 2025-12-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_options_student_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='srn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Student Registration Number'),
        ),
    ]
