# Generated by Django 6.0 on 2025-12-22 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0011_expense_payment_type'),
        ('students', '0011_alter_student_srn'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionClassStudentMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Student Registration Number')),
                ('promoted_date', models.DateTimeField(blank=True, null=True, verbose_name='Promotion Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_student_maps', to='dailyLedger.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_class_maps', to='students.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_student_maps', to='students.class')),
            ],
            options={
                'verbose_name_plural': 'Session Class Student Maps',
                'ordering': ['session', 'student_class__age', 'student__first_name'],
                'unique_together': {('session', 'student_class', 'student')},
            },
        ),
    ]
