# Generated by Django 6.0 on 2025-12-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='transport_method',
            field=models.BooleanField(default=False, verbose_name='Uses School Bus'),
        ),
    ]
