# Generated by Django 6.0 on 2025-12-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('qualification', models.CharField(blank=True, max_length=120)),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('previous_institute', models.CharField(blank=True, max_length=150)),
                ('post', models.CharField(blank=True, max_length=120)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('base_salary_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('left', 'Left')], default='active', max_length=20)),
                ('leaves_entitled', models.IntegerField(default=0)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('emp_image', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
