# Generated by Django 6.0 on 2025-12-28 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0002_feesstructure_head_income_session_and_more'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name (can be duplicate, used for UI only). If blank, name is used.', max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_no',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='role_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ManualSalaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_type', models.CharField(choices=[('salary', 'Salary'), ('old_due', 'Old Due'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount in rupees', max_digits=10)),
                ('month', models.CharField(help_text='Format: YYYY-MM (e.g., 2024-01)', max_length=7)),
                ('note', models.TextField(blank=True, help_text='Optional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_salary_records', to='employees.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_salary_data', to='dailyLedger.session')),
            ],
            options={
                'verbose_name_plural': 'Manual Salary Data',
                'ordering': ['-session', '-month', 'employee__name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half-day', 'Half Day'), ('leave', 'Leave')], default='present', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance', to='dailyLedger.session')),
            ],
            options={
                'ordering': ['-date', 'employee__name'],
                'unique_together': {('session', 'date', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default='2024-01', help_text='Format: YYYY-MM (e.g., 2024-01)', max_length=7)),
                ('paid_days', models.DecimalField(decimal_places=2, default=0, help_text='Number of days to be paid', max_digits=5)),
                ('payable_salary', models.DecimalField(decimal_places=2, default=0, help_text='Calculated monthly payable salary', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyLedger.session')),
            ],
            options={
                'ordering': ['-session', '-month', 'employee__name'],
                'unique_together': {('session', 'employee', 'month')},
            },
        ),
    ]
