# Generated by Django 6.0 on 2026-03-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0004_add_employee_fk_to_expense'),
        ('employees', '0002_employee_display_name_employee_emp_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('payable_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Final validated salary', max_digits=10, null=True)),
                ('old_dues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='employees.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='dailyLedger.session')),
            ],
            options={
                'ordering': ['employee__name'],
                'unique_together': {('session', 'employee', 'month')},
            },
        ),
    ]
