# Generated by Django 6.0 on 2026-03-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeepayrollentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualsalarydata',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='manualsalarydata',
            name='session',
        ),
        migrations.DeleteModel(
            name='EmployeeRegister',
        ),
        migrations.DeleteModel(
            name='ManualSalaryData',
        ),
    ]
