# Generated by Django 6.0 on 2025-12-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0011_expense_payment_type'),
        ('employees', '0003_employee_gender_employee_role_employee_role_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_days', models.DecimalField(decimal_places=2, default=0, help_text='Number of days to be paid', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyLedger.session')),
            ],
            options={
                'ordering': ['-session', 'employee__name'],
                'unique_together': {('session', 'employee')},
            },
        ),
    ]
