# Generated by Django 6.0 on 2025-12-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0011_expense_payment_type'),
        ('employees', '0004_employeeregister'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeregister',
            options={'ordering': ['-session', '-month', 'employee__name']},
        ),
        migrations.AlterUniqueTogether(
            name='employeeregister',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeeregister',
            name='month',
            field=models.CharField(default='2024-01', help_text='Format: YYYY-MM (e.g., 2024-01)', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='employeeregister',
            unique_together={('session', 'employee', 'month')},
        ),
    ]
