# Generated by Django 6.0 on 2026-03-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_delete_employeeregister_manualsalarydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayrollentry',
            name='manual_leave_days',
            field=models.IntegerField(blank=True, help_text='Override: leave days if attendance register not filled', null=True),
        ),
        migrations.AddField(
            model_name='employeepayrollentry',
            name='manual_work_days',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Override: working days if attendance register not filled', max_digits=5, null=True),
        ),
    ]
