# Generated by Django 6.0 on 2025-12-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employeeregister_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregister',
            name='payable_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated monthly payable salary', max_digits=10),
        ),
    ]
