# Generated by Django 6.0 on 2025-12-23 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0013_feesstructure'),
        ('employees', '0007_employeeattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSalaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_type', models.CharField(choices=[('salary', 'Salary'), ('old_due', 'Old Due')], max_length=20)),
                ('month', models.CharField(help_text='Format: YYYY-MM (e.g., 2024-01)', max_length=7)),
                ('note', models.TextField(blank=True, help_text='Optional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_salary_records', to='employees.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_salary_data', to='dailyLedger.session')),
            ],
            options={
                'verbose_name_plural': 'Manual Salary Data',
                'ordering': ['-session', '-month', 'employee__name'],
            },
        ),
    ]
