# Generated by Django 6.0 on 2025-12-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_manualsalarydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualsalarydata',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in rupees', max_digits=10),
        ),
    ]
