# Generated by Django 6.0 on 2025-12-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_manualsalarydata_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualsalarydata',
            name='amount_type',
            field=models.CharField(choices=[('salary', 'Salary'), ('old_due', 'Old Due'), ('other', 'Other')], max_length=20),
        ),
    ]
