# Generated by Django 6.0 on 2025-12-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_manualsalarydata_amount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name (can be duplicate, used for UI only). If blank, name is used.', max_length=120),
        ),
    ]
