from django.urls import path
from .views import (
    expenses_home,
    income_home,
    delete_expense,
    delete_income,
    heads_home,
    delete_head,
    sessions_home,
    delete_session,
    bulk_import,
    download_template,
    bulk_import_ledger,
    download_ledger_template,
    fees_structure_list,
    add_fees_structure,
    edit_fees_structure,
    delete_fees_structure,
    api_get_classes,
    api_get_students,
    api_get_student_srn,
    api_get_fee_account,
    session_ledger_report,
    export_expenses_csv,
    delete_all_expenses,
    export_income_csv,
    delete_all_income,
    export_heads_csv,
    delete_all_heads,
)

urlpatterns = [
    path("", expenses_home, name="expenses_home"),
    path("delete/<int:pk>/", delete_expense, name="delete_expense"),
    path("export-csv/", export_expenses_csv, name="export_expenses_csv"),
    path("delete-all/", delete_all_expenses, name="delete_all_expenses"),
    path("heads/", heads_home, name="heads_home"),
    path("heads/delete/<int:pk>/", delete_head, name="delete_head"),
    path("heads/export-csv/", export_heads_csv, name="export_heads_csv"),
    path("heads/delete-all/", delete_all_heads, name="delete_all_heads"),
    path("heads/bulk-import/", bulk_import, name="bulk_import"),
    path("heads/download-template/", download_template, name="download_template"),
    path("sessions/", sessions_home, name="sessions_home"),
    path("sessions/delete/<int:pk>/", delete_session, name="delete_session"),
    path("bulk-import-ledger/", bulk_import_ledger, name="bulk_import_ledger"),
    path("download-ledger-template/", download_ledger_template, name="download_ledger_template"),
    path("session-ledger-report/", session_ledger_report, name="session_ledger_report"),
    path("income/", income_home, name="income_home"),
    path("income/delete/<int:pk>/", delete_income, name="delete_income"),
    path("income/export-csv/", export_income_csv, name="export_income_csv"),
    path("income/delete-all/", delete_all_income, name="delete_all_income"),
    
    # Fees Structure URLs
    path("fees-structure/", fees_structure_list, name="fees_structure_list"),
    path("fees-structure/add/", add_fees_structure, name="add_fees_structure"),
    path("fees-structure/edit/<int:pk>/", edit_fees_structure, name="edit_fees_structure"),
    path("fees-structure/delete/<int:pk>/", delete_fees_structure, name="delete_fees_structure"),
    
    # API Endpoints for cascading dropdowns
    path("api/classes/<int:session_id>/", api_get_classes, name="api_get_classes"),
    path("api/students/<int:session_id>/<int:class_id>/", api_get_students, name="api_get_students"),
    path("api/student-srn/<int:student_id>/", api_get_student_srn, name="api_get_student_srn"),
    path("api/fee-account/<str:srn>/", api_get_fee_account, name="api_get_fee_account"),
]
