# Generated by Django 6.0 on 2025-12-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_tuition', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('fee_tc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Fee TC')),
                ('fee_admission', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('book_set', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('book_diary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('book_other', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('uniform_shirt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('uniform_pant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('uniform_tie', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('uniform_belt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('uniform_id_card', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-session', 'class_code'],
            },
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_head', models.CharField(max_length=80)),
                ('head', models.CharField(max_length=80)),
                ('sub_head', models.CharField(blank=True, max_length=80)),
                ('details', models.TextField(blank=True, help_text='Additional details or notes for this head')),
                ('ledger_type', models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], default='Expense', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['major_head', 'head', 'sub_head'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, max_length=60)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.CharField(blank=True, max_length=200)),
                ('major_head', models.CharField(blank=True, max_length=80)),
                ('head', models.CharField(blank=True, max_length=80)),
                ('sub_head', models.CharField(blank=True, help_text='For salary: employee name. For others: vendor/account name.', max_length=80)),
                ('payment_type', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Against Credit', 'Against Credit')], default='Cash', max_length=20, verbose_name='Transaction Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(blank=True, choices=[('', '-- Select Status --'), ('next_session', 'Next Session'), ('current_session', 'Current Session'), ('old_session', 'Old Session')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-session'],
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_type',
        ),
        migrations.AddField(
            model_name='expense',
            name='details',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expense',
            name='head',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='expense',
            name='major_head',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Against Credit', 'Against Credit')], default='Cash', max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AddField(
            model_name='expense',
            name='sub_head',
            field=models.CharField(blank=True, help_text='For salary: employee name. For others: vendor/account name.', max_length=80),
        ),
        migrations.AddField(
            model_name='expense',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
