# Generated by Django 6.0 on 2025-12-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_type',
        ),
        migrations.AddField(
            model_name='expense',
            name='head',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='expense',
            name='major_head',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='remark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expense',
            name='sub_head',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='expense',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
