# Generated by Django 6.0 on 2025-12-28 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0002_feesstructure_head_income_session_and_more'),
        ('students', '0002_class_feesaccount_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesstructure',
            name='class_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_structures', to='students.class'),
        ),
        migrations.AlterUniqueTogether(
            name='head',
            unique_together={('major_head', 'head', 'sub_head')},
        ),
        migrations.AddField(
            model_name='income',
            name='fees_account',
            field=models.ForeignKey(blank=True, help_text='Link to fees account (for student fee income tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.feesaccount'),
        ),
        migrations.AddField(
            model_name='income',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailyLedger.session'),
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_structures', to='dailyLedger.session'),
        ),
        migrations.AddField(
            model_name='expense',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailyLedger.session'),
        ),
        migrations.AlterUniqueTogether(
            name='feesstructure',
            unique_together={('session', 'class_code')},
        ),
    ]
