# Generated by Django 6.0 on 2025-12-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0002_remove_expense_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-id']},
        ),
    ]
