# Generated by Django 6.0 on 2026-03-14 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0003_feesstructure_class_code_alter_head_unique_together_and_more'),
        ('employees', '0002_employee_display_name_employee_emp_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Link to employee (for salary expense tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
    ]
