# Generated by Django 6.0 on 2025-12-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0003_alter_expense_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_head', models.CharField(max_length=80)),
                ('head', models.CharField(max_length=80)),
                ('sub_head', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['major_head', 'head', 'sub_head'],
                'unique_together': {('major_head', 'head', 'sub_head')},
            },
        ),
    ]
