# Generated by Django 6.0 on 2025-12-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0003_feesstructure_class_code_alter_head_unique_together_and_more'),
    ]

    operations = [
    ]
