# Generated by Django 6.0 on 2026-04-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0004_add_employee_fk_to_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesstructure',
            name='uniform_hoody',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='uniform_sweater',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='uniform_t_shirt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
