# Generated by Django 6.0 on 2025-12-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0004_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='head_type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], default='Expense', max_length=10),
        ),
    ]
