# Generated by Django 6.0 on 2025-12-17 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0007_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailyLedger.session'),
        ),
    ]
