# Generated by Django 6.0 on 2025-12-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0008_expense_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='remark',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='head_type',
            new_name='ledger_type',
        ),
        migrations.RenameField(
            model_name='head',
            old_name='head_type',
            new_name='ledger_type',
        ),
        migrations.AlterField(
            model_name='expense',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
