# Generated by Django 6.0 on 2025-12-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0009_rename_fields_to_match_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='account',
            new_name='account_name',
        ),
    ]
