# Generated by Django 6.0 on 2025-12-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0010_rename_account_to_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Against Credit', 'Against Credit')], default='Cash', max_length=20),
        ),
    ]
