# Generated by Django 6.0 on 2025-12-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0011_expense_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(blank=True, choices=[('', '-- Select Status --'), ('next_session', 'Next Session'), ('current_session', 'Current Session'), ('old_session', 'Old Session')], default='', max_length=20),
        ),
    ]
