# Generated by Django 6.0 on 2025-12-23 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0012_alter_session_status'),
        ('students', '0014_alter_student_transport_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_tuition', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('fee_tc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Fee TC')),
                ('fee_admission', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('book_set', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('book_diary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('book_other', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('uniform_shirt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('uniform_pant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('uniform_tie', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('uniform_belt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('uniform_id_card', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_structures', to='students.class')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_structures', to='dailyLedger.session')),
            ],
            options={
                'ordering': ['-session', 'class_code'],
                'unique_together': {('session', 'class_code')},
            },
        ),
    ]
