# Generated by Django 6.0 on 2025-12-24 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0013_feesstructure'),
        ('employees', '0010_alter_manualsalarydata_amount_type'),
        ('students', '0015_studentattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='account_name',
        ),
        migrations.AddField(
            model_name='expense',
            name='account_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('student_fees', 'Student Fees Account'), ('vendor', 'Vendor'), ('bank', 'Bank Account'), ('other', 'Other/General')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='fees_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='students.feesaccount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='other_account_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Account Name (for Other/General accounts)'),
        ),
    ]
