# Generated by Django 6.0 on 2025-12-24 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0014_remove_expense_account_name_expense_account_type_and_more'),
        ('employees', '0010_alter_manualsalarydata_amount_type'),
        ('students', '0015_studentattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='ledger_type',
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='fees_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.feesaccount'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, max_length=60)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.CharField(blank=True, max_length=200)),
                ('account_type', models.CharField(choices=[('employee', 'Employee'), ('student_fees', 'Student Fees Account'), ('vendor', 'Vendor'), ('bank', 'Bank Account'), ('other', 'Other/General')], default='other', max_length=20)),
                ('other_account_name', models.CharField(blank=True, max_length=200, verbose_name='Account Name (for Other/General accounts)')),
                ('major_head', models.CharField(blank=True, max_length=80)),
                ('head', models.CharField(blank=True, max_length=80)),
                ('sub_head', models.CharField(blank=True, max_length=80)),
                ('payment_type', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Against Credit', 'Against Credit')], default='Cash', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('fees_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.feesaccount')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailyLedger.session')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
