# Generated by Django 6.0 on 2025-12-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0015_remove_expense_ledger_type_alter_expense_employee_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DELETE FROM dailyledger_expense;',
            reverse_sql='-- No reverse operation for delete',
        ),
    ]
