# Generated by Django 6.0 on 2025-12-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0016_truncate_expense_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='fees_account',
        ),
        migrations.RemoveField(
            model_name='income',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='income',
            name='fees_account',
        ),
        migrations.AlterField(
            model_name='expense',
            name='other_account_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='income',
            name='other_account_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Account Name'),
        ),
    ]
