# Generated by Django 6.0 on 2025-12-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0017_remove_expense_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='other_account_name',
        ),
        migrations.RemoveField(
            model_name='income',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='income',
            name='other_account_name',
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Against Credit', 'Against Credit')], default='Cash', max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='sub_head',
            field=models.CharField(blank=True, help_text='For salary: employee name. For others: vendor/account name.', max_length=80),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Against Credit', 'Against Credit')], default='Cash', max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='income',
            name='sub_head',
            field=models.CharField(blank=True, help_text='For salary: employee name. For others: vendor/account name.', max_length=80),
        ),
    ]
