# Generated by Django 6.0 on 2025-12-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0018_remove_expense_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
