# Generated by Django 6.0 on 2025-12-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0019_head_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='details',
            field=models.TextField(blank=True, help_text='Additional details or notes for this head'),
        ),
    ]
