# Generated by Django 6.0 on 2025-12-26 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0020_head_details'),
        ('students', '0015_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='fees_account',
            field=models.ForeignKey(blank=True, help_text='Link to fees account (for student fee income tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.feesaccount'),
        ),
    ]
