# Generated by Django 6.0 on 2025-12-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyLedger', '0021_income_fees_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Against Credit', 'Against Credit')], default='', max_length=20, null=True),
        ),
    ]
