# Generated by Django 6.0 on 2025-12-28 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('principal', 'Principal'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('support_staff', 'Support Staff')], help_text='Unique identifier for the role', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Display name for UI', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of role responsibilities')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive roles cannot be assigned to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions assigned to this role', related_name='roles', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the user', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender', max_length=1)),
                ('profile_image', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('department', models.CharField(blank=True, help_text='Department or designation', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='Last login IP address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
