from django.urls import path
from .views import (
    employees_home, delete_employee, bulk_import_employees, download_employees_template, 
    employee_register, delete_register, manual_salary_data, delete_manual_salary_data, 
    bulk_import_manual_salary_data, download_manual_salary_data_template, 
    new_employee_statements, salary_statement_view, pay_slip_view, employee_monthly_statement, 
    employee_yearly_statement, employees_monthly_statement, employees_yearly_statement, 
    select_statement_type, select_employee_monthly_params, select_employee_yearly_params, 
    select_employees_monthly_params, select_employees_yearly_params, select_pay_slip_params, 
    employees_summary_statement, select_ledger_statement_params, ledger_statement, 
    select_expense_statement_params, expense_statement, select_income_statement_params, 
    income_statement, full_statement, select_full_statement_params, employee_attendance, 
    delete_attendance, attendance_rally, employee_salary_statement, select_employee_salary_statement_params,
    employee_salary_payment_details, select_employee_salary_payment_details_params, employees_salary_statement,
    export_employees_csv, delete_all_employees
)
from . import views

urlpatterns = [
    path("", employees_home, name="employees_home"),
    path("delete/<int:pk>/", delete_employee, name="delete_employee"),
    path("export-csv/", export_employees_csv, name="export_employees_csv"),
    path("delete-all/", delete_all_employees, name="delete_all_employees"),
    path("bulk-import/", bulk_import_employees, name="bulk_import_employees"),
    path("download-template/", download_employees_template, name="download_employees_template"),
    path("manual-salary-data/", manual_salary_data, name="manual_salary_data"),
    path("manual-salary-data/bulk-import/", bulk_import_manual_salary_data, name="bulk_import_manual_salary_data"),
    path("manual-salary-data/download-template/", download_manual_salary_data_template, name="download_manual_salary_data_template"),
    path("manual-salary-data/delete/<int:pk>/", delete_manual_salary_data, name="delete_manual_salary_data"),
    path("view/", views.employees_view, name="employees_view"),
    path("register/", employee_register, name="employee_register"),
    path("register/delete/<int:pk>/", delete_register, name="delete_register"),
    path("select-type/", select_statement_type, name="select_statement_type"),
    path("select-type/employee-monthly/", select_employee_monthly_params, name="select_employee_monthly_params"),
    path("select-type/employee-yearly/", select_employee_yearly_params, name="select_employee_yearly_params"),
    path("select-type/employees-monthly/", select_employees_monthly_params, name="select_employees_monthly_params"),
    path("select-type/employees-yearly/", select_employees_yearly_params, name="select_employees_yearly_params"),
    path("select-type/pay-slip/", select_pay_slip_params, name="select_pay_slip_params"),
    path("select-type/salary-statement/", select_employee_salary_statement_params, name="select_employee_salary_statement_params"),
    path("select-type/salary-payment-details/", select_employee_salary_payment_details_params, name="select_employee_salary_payment_details_params"),
    path("select-type/ledger-statement/", select_ledger_statement_params, name="select_ledger_statement_params"),
    path("select-type/expense-statement/", select_expense_statement_params, name="select_expense_statement_params"),
    path("select-type/income-statement/", select_income_statement_params, name="select_income_statement_params"),
    path("new-statements/", new_employee_statements, name="new_employee_statements"),
    path("salary-statement/", salary_statement_view, name="salary_statement_view"),
    path("salary-statement-full/", employee_salary_statement, name="employee_salary_statement_full"),
    path("salary-statement/<int:emp_id>/", employee_salary_statement, name="employee_salary_statement"),
    path("employees-salary-statement/", employees_salary_statement, name="employees_salary_statement"),
    path("salary-payment-details/<int:emp_id>/", employee_salary_payment_details, name="employee_salary_payment_details"),
    path("pay-slip/", pay_slip_view, name="pay_slip_view"),
    path("employee-monthly/", employee_monthly_statement, name="employee_monthly_statement"),
    path("employee-yearly/", employee_yearly_statement, name="employee_yearly_statement"),
    path("employees-monthly/", employees_monthly_statement, name="employees_monthly_statement"),
    path("employees-yearly/", employees_yearly_statement, name="employees_yearly_statement"),
    path("employees-summary/", employees_summary_statement, name="employees_summary_statement"),
    path("ledger-statement/", ledger_statement, name="ledger_statement"),
    path("expense-statement/", expense_statement, name="expense_statement"),
    path("income-statement/", income_statement, name="income_statement"),
    path("select-type/full-statement/", select_full_statement_params, name="select_full_statement_params"),
    path("full-statement/", full_statement, name="full_statement"),
    path("attendance/", employee_attendance, name="employee_attendance"),
    path("attendance/delete/<int:pk>/", delete_attendance, name="delete_attendance"),
    path("attendance-rally/", attendance_rally, name="attendance_rally"),
]